/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CreateFamilyRouteImport } from './routes/create-family'
import { Route as JoinFamilyRouteImport } from './routes/join-family'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppChangesRouteImport } from './routes/app/changes'
import { Route as AppMembersRouteImport } from './routes/app/members'
import { Route as AppMemoriesRouteImport } from './routes/app/memories'
import { Route as AppPhotosRouteImport } from './routes/app/photos'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTreeRouteImport } from './routes/app/tree'
import { Route as CreateFamilyBackupRouteImport } from './routes/create-family.backup'
import { Route as AppPeoplePersonIdRouteImport } from './routes/app/people.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFamilyRoute = CreateFamilyRouteImport.update({
  id: '/create-family',
  path: '/create-family',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinFamilyRoute = JoinFamilyRouteImport.update({
  id: '/join-family',
  path: '/join-family',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPhotosRoute = AppPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTreeRoute = AppTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AppRouteRoute,
} as any)
const CreateFamilyBackupRoute = CreateFamilyBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => CreateFamilyRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/create-family': typeof CreateFamilyRouteWithChildren
  '/join-family': typeof JoinFamilyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/changes': typeof AppChangesRoute
  '/app/members': typeof AppMembersRoute
  '/app/memories': typeof AppMemoriesRoute
  '/app/photos': typeof AppPhotosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tree': typeof AppTreeRoute
  '/create-family/backup': typeof CreateFamilyBackupRoute
  '/app/': typeof AppIndexRoute
  '/app/people/$personId': typeof AppPeoplePersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-family': typeof CreateFamilyRouteWithChildren
  '/join-family': typeof JoinFamilyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/changes': typeof AppChangesRoute
  '/app/members': typeof AppMembersRoute
  '/app/memories': typeof AppMemoriesRoute
  '/app/photos': typeof AppPhotosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tree': typeof AppTreeRoute
  '/create-family/backup': typeof CreateFamilyBackupRoute
  '/app': typeof AppIndexRoute
  '/app/people/$personId': typeof AppPeoplePersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/create-family': typeof CreateFamilyRouteWithChildren
  '/join-family': typeof JoinFamilyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/changes': typeof AppChangesRoute
  '/app/members': typeof AppMembersRoute
  '/app/memories': typeof AppMemoriesRoute
  '/app/photos': typeof AppPhotosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tree': typeof AppTreeRoute
  '/create-family/backup': typeof CreateFamilyBackupRoute
  '/app/': typeof AppIndexRoute
  '/app/people/$personId': typeof AppPeoplePersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create-family'
    | '/join-family'
    | '/login'
    | '/register'
    | '/app/changes'
    | '/app/members'
    | '/app/memories'
    | '/app/photos'
    | '/app/settings'
    | '/app/tree'
    | '/create-family/backup'
    | '/app/'
    | '/app/people/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-family'
    | '/join-family'
    | '/login'
    | '/register'
    | '/app/changes'
    | '/app/members'
    | '/app/memories'
    | '/app/photos'
    | '/app/settings'
    | '/app/tree'
    | '/create-family/backup'
    | '/app'
    | '/app/people/$personId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/create-family'
    | '/join-family'
    | '/login'
    | '/register'
    | '/app/changes'
    | '/app/members'
    | '/app/memories'
    | '/app/photos'
    | '/app/settings'
    | '/app/tree'
    | '/create-family/backup'
    | '/app/'
    | '/app/people/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CreateFamilyRoute: typeof CreateFamilyRouteWithChildren
  JoinFamilyRoute: typeof JoinFamilyRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-family': {
      id: '/create-family'
      path: '/create-family'
      fullPath: '/create-family'
      preLoaderRoute: typeof CreateFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-family': {
      id: '/join-family'
      path: '/join-family'
      fullPath: '/join-family'
      preLoaderRoute: typeof JoinFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/changes': {
      id: '/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/memories': {
      id: '/app/memories'
      path: '/memories'
      fullPath: '/app/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/photos': {
      id: '/app/photos'
      path: '/photos'
      fullPath: '/app/photos'
      preLoaderRoute: typeof AppPhotosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tree': {
      id: '/app/tree'
      path: '/tree'
      fullPath: '/app/tree'
      preLoaderRoute: typeof AppTreeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/create-family/backup': {
      id: '/create-family/backup'
      path: '/backup'
      fullPath: '/create-family/backup'
      preLoaderRoute: typeof CreateFamilyBackupRouteImport
      parentRoute: typeof CreateFamilyRoute
    }
    '/app/people/$personId': {
      id: '/app/people/$personId'
      path: '/people/$personId'
      fullPath: '/app/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppChangesRoute: typeof AppChangesRoute
  AppMembersRoute: typeof AppMembersRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppPhotosRoute: typeof AppPhotosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTreeRoute: typeof AppTreeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChangesRoute: AppChangesRoute,
  AppMembersRoute: AppMembersRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppPhotosRoute: AppPhotosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTreeRoute: AppTreeRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CreateFamilyRouteChildren {
  CreateFamilyBackupRoute: typeof CreateFamilyBackupRoute
}

const CreateFamilyRouteChildren: CreateFamilyRouteChildren = {
  CreateFamilyBackupRoute: CreateFamilyBackupRoute,
}

const CreateFamilyRouteWithChildren = CreateFamilyRoute._addFileChildren(
  CreateFamilyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CreateFamilyRoute: CreateFamilyRouteWithChildren,
  JoinFamilyRoute: JoinFamilyRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
